### ISSUE TITLE
TypeError: Common.forCustomChain is not a function

### ISSUE THREAD

**Issue by macelai** [odanado/aws-kms-provider#420]
Hey, it's me again! After upgrading to 0.5.0 I got this error trying to sign a transaction. Here it is the stack trace:

```
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Common.forCustomChain is not a function
      at KmsProvider.getTransactionOptions (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:118:29)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async KmsProvider.createTransaction (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:140:18)
      at async KmsProvider.signTransaction (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:77:16)
}  reason:  TypeError: Common.forCustomChain is not a function
    at KmsProvider.getTransactionOptions (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:118:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async KmsProvider.createTransaction (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:140:18)
    at async KmsProvider.signTransaction (file:///Users/viniciusmacelai/git/nft-be/node_modules/aws-kms-provider/dist/index.js:77:16)
```

**Comment by odanado** [comment]
I have confirmed that this error is reproduced with the following code.

```ts
async function main() {
  const keyId = "e9005048-475f-4767-9f2d-0d1fb0c89caf";
  const region = "us-east-1";
  const endpoint =
    "https://ropsten.infura.io/v3/bd35010d62134981a9e82dff4708728b";

  const provider = new KmsProvider(
    endpoint,
    { region, keyIds: [keyId] },
    { chainId: 3, networkId: 3, chainName: "ropsten" }
  );
  const web3 = new Web3(provider);

  const [address] = await web3.eth.getAccounts();
  await web3.eth.sendTransaction({
    from: address,
    to: address,
  });
  provider["engine"].stop();
}
```


I'll start investigating the cause.

**Comment by odanado** [comment]
I think I can solve this problem by using https://www.npmjs.com/package/node-cjs-interop.

**Comment by odanado** [comment]
@macelai Thank you for reporting.
This issue has been solved at `aws-kms-provider@0.5.1`.

**Comment by macelai** [comment]
Thanks again, I can confirm it was fixed.
